# Generated by Django 5.2.7 on 2025-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_ORM', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='nombre_idx'),
        ),
    ]
